# Generated by Django 5.2.6 on 2026-01-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="image",
            field=models.CharField(max_length=100),
        ),
    ]
