# Generated by Django 5.2.6 on 2026-01-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_app_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="pod",
            name="cleanup_job_name",
            field=models.CharField(
                blank=True,
                help_text="K8s Job name for scheduled cleanup",
                max_length=255,
                null=True,
            ),
        ),
    ]
