# Generated by Django 6.0.4 on 2026-05-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_pod_cleanup_job_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="country",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
