# Generated by Django 6.0.4 on 2026-06-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_useractivity_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="app_type",
            field=models.CharField(
                choices=[("novnc", "noVNC"), ("webrtc", "WebRTC (Selkies)")],
                default="novnc",
                help_text="Streaming type: noVNC web page or self-hosted WebRTC (Selkies) UI",
                max_length=10,
            ),
        ),
    ]
