# Generated by Django 6.0.4 on 2026-06-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_app_app_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="session_duration_minutes",
            field=models.PositiveSmallIntegerField(
                default=5, help_text="Minutes before the session is auto-stopped/cleaned up."
            ),
        ),
    ]
